export enum CharacterID {
    ALBEDO, ALHAITAM, ALOY, AMBER, ARATAKI_ITTO, ARLECCHINO, BAIZHU, BARBARA, BEIDOU, BENNETT,
    CANDACE, CHARLOTTE, CHEVREUSE, CHIORI, CHONGYUN, CLORINDE, COLLEI, CYNO, DEHYA, DILUC,
    DIONA, DORI, EULA, FARUZAN, FISCHL, FREMINET, FURINA, GAMING, GANYU, GOROU,
    HU_TAO, JEAN, KAEDEHARA_KAZUHA, KAEYA, KAMISATO_AYAKA, KAMISATO_AYATO, KAVEH, KEQING, KIRARA, KLEE,
    KUJOU_SARA, KUKI_SHINOBU, LAYLA, LISA, LYNETTE, LYNEY, MIKA, MONA, NAHIDA, NAVIA,
    NEUVILLETTE, NILOU, NINGGUANG, NOELLE, QIQI, RAIDEN_SHOGUN, RAZOR, ROSARIA, SANGONOMIYA_KOKOMI, SAYU,
    SETHOS, SHENHE, SHIKANOIN_HEIZOU, SUCROSE, TARTAGLIA, THOMA, TIGHNARI, TRAVELER, VENTI, WANDERER,
    WRIOTHESLEY, XIANGLING, XIANYUN, XIAO, XINQGIU, XINYAN, YAE_MIKO, YANFEI, YAOYAO, YELAN,
    YOIMIYA, YUN_JIN, ZHONGLI, NONE
}

export enum CharacterState { DISABLED = "disabled", DESELECTED = "deselected", SELECTED = "selected", DEFAULT = DESELECTED }

export const allCharacters = [
    CharacterID.ALBEDO, CharacterID.ALHAITAM, CharacterID.ALOY, CharacterID.AMBER, CharacterID.ARATAKI_ITTO,
    CharacterID.ARLECCHINO, CharacterID.BAIZHU, CharacterID.BARBARA, CharacterID.BEIDOU, CharacterID.BENNETT,
    CharacterID.CANDACE, CharacterID.CHARLOTTE, CharacterID.CHEVREUSE, CharacterID.CHIORI, CharacterID.CHONGYUN,
    CharacterID.CLORINDE, CharacterID.COLLEI, CharacterID.CYNO, CharacterID.DEHYA, CharacterID.DILUC,
    CharacterID.DIONA, CharacterID.DORI, CharacterID.EULA, CharacterID.FARUZAN, CharacterID.FISCHL,
    CharacterID.FREMINET, CharacterID.FURINA, CharacterID.GAMING, CharacterID.GANYU, CharacterID.GOROU,
    CharacterID.HU_TAO, CharacterID.JEAN, CharacterID.KAEDEHARA_KAZUHA, CharacterID.KAEYA,
    CharacterID.KAMISATO_AYAKA, CharacterID.KAMISATO_AYATO, CharacterID.KAVEH, CharacterID.KEQING, CharacterID.KIRARA, CharacterID.KLEE,
    CharacterID.KUJOU_SARA, CharacterID.KUKI_SHINOBU, CharacterID.LAYLA, CharacterID.LISA,
    CharacterID.LYNETTE, CharacterID.LYNEY, CharacterID.MIKA, CharacterID.MONA, CharacterID.NAHIDA, CharacterID.NAVIA,
    CharacterID.NEUVILLETTE, CharacterID.NILOU, CharacterID.NINGGUANG, CharacterID.NOELLE, CharacterID.QIQI,
    CharacterID.RAIDEN_SHOGUN, CharacterID.RAZOR, CharacterID.ROSARIA, CharacterID.SANGONOMIYA_KOKOMI, CharacterID.SAYU,
    CharacterID.SETHOS, CharacterID.SHENHE, CharacterID.SHIKANOIN_HEIZOU, CharacterID.SUCROSE, CharacterID.TARTAGLIA,
    CharacterID.THOMA, CharacterID.TIGHNARI, CharacterID.TRAVELER, CharacterID.VENTI, CharacterID.WANDERER,
    CharacterID.WRIOTHESLEY, CharacterID.XIANGLING, CharacterID.XIANYUN, CharacterID.XIAO, CharacterID.XINQGIU,
    CharacterID.XINYAN, CharacterID.YAE_MIKO, CharacterID.YANFEI, CharacterID.YAOYAO, CharacterID.YELAN,
    CharacterID.YOIMIYA, CharacterID.YUN_JIN, CharacterID.ZHONGLI
]

export enum Weapon { BOW = "Bow", CATALYST = "Catalyst", CLAYMORE = "Claymore", POLEARM = "Polearm", SWORD = "Sword"}
export enum Element { ANEMO = "Anemo", CRYO = "Cryo", DENDRO = "Dendro", ELECTRO = "Electro", GEO = "Geo", HYDRO = "Hydro", PYRO = "Pyro" }

export interface CharacterDataEntry {
    name: string,
    element: Element,
    weapon: Weapon,
    rarity: number
}

export const charactersData = [
    {name: "Albedo", element: Element.GEO, weapon: Weapon.SWORD, rarity: 5},
    {name: "Alhaitam", element: Element.ANEMO, weapon: Weapon.BOW, rarity: 4},
    {name: "Aloy", element: Element.CRYO, weapon: Weapon.BOW, rarity: 5},
    {name: "Amber", element: Element.PYRO, weapon: Weapon.BOW, rarity: 4},
    {name: "Arataki Itto", element: Element.GEO, weapon: Weapon.CLAYMORE, rarity: 5},
    {name: "Arlecchino", element: Element.HYDRO, weapon: Weapon.CATALYST, rarity: 4},
    {name: "Baizhu", element: Element.DENDRO, weapon: Weapon.CATALYST, rarity: 5},
    {name: "Barbara", element: Element.HYDRO, weapon: Weapon.CATALYST, rarity: 4},
    {name: "Beidou", element: Element.ELECTRO, weapon: Weapon.CLAYMORE, rarity: 4},
    {name: "Bennett", element: Element.PYRO, weapon: Weapon.SWORD, rarity: 4},
    {name: "Candace", element: Element.CRYO, weapon: Weapon.CLAYMORE, rarity: 4},
    {name: "Charlotte", element: Element.HYDRO, weapon: Weapon.CLAYMORE, rarity: 4},
    {name: "Chevreuse", element: Element.GEO, weapon: Weapon.POLEARM, rarity: 4},
    {name: "Chiori", element: Element.ELECTRO, weapon: Weapon.SWORD, rarity: 4},
    {name: "Chongyun", element: Element.CRYO, weapon: Weapon.CLAYMORE, rarity: 4},
    {name: "Clorinde", element: Element.ANEMO, weapon: Weapon.SWORD, rarity: 4},
    {name: "Collei", element: Element.DENDRO, weapon: Weapon.BOW, rarity: 4},
    {name: "Cyno", element: Element.CRYO, weapon: Weapon.POLEARM, rarity: 4},
    {name: "Dehya", element: Element.GEO, weapon: Weapon.CATALYST, rarity: 4},
    {name: "Diluc", element: Element.PYRO, weapon: Weapon.CLAYMORE, rarity: 5},
    {name: "Diona", element: Element.CRYO, weapon: Weapon.BOW, rarity: 4},
    {name: "Dori", element: Element.HYDRO, weapon: Weapon.SWORD, rarity: 4},
    {name: "Eula", element: Element.CRYO, weapon: Weapon.CLAYMORE, rarity: 5},
    {name: "Furuzan", element: Element.PYRO, weapon: Weapon.POLEARM, rarity: 4},
    {name: "Fischl", element: Element.ELECTRO, weapon: Weapon.BOW, rarity: 4},
    {name: "Freminet", element: Element.CRYO, weapon: Weapon.CLAYMORE, rarity: 4},
    {name: "Furina", element: Element.PYRO, weapon: Weapon.CATALYST, rarity: 4},
    {name: "Gaming", element: Element.ELECTRO, weapon: Weapon.CATALYST, rarity: 4},
    {name: "Ganyu", element: Element.CRYO, weapon: Weapon.BOW, rarity: 5},
    {name: "Gorou", element: Element.GEO, weapon: Weapon.POLEARM, rarity: 4},
    {name: "Hu Tao", element: Element.PYRO, weapon: Weapon.POLEARM, rarity: 5},
    {name: "Jean", element: Element.ANEMO, weapon: Weapon.SWORD, rarity: 5},
    {name: "Kaedehara Kazuha", element: Element.ANEMO, weapon: Weapon.SWORD, rarity: 5},
    {name: "Kaeya", element: Element.CRYO, weapon: Weapon.SWORD, rarity: 4},
    {name: "Kamisato Ayaka", element: Element.CRYO, weapon: Weapon.SWORD, rarity: 5},
    {name: "Kamisato Ayato", element: Element.ELECTRO, weapon: Weapon.SWORD, rarity: 4},
    {name: "Kaveh", element: Element.GEO, weapon: Weapon.CLAYMORE, rarity: 4},
    {name: "Keqing", element: Element.ELECTRO, weapon: Weapon.SWORD, rarity: 5},
    {name: "Kirara", element: Element.ELECTRO, weapon: Weapon.CATALYST, rarity: 4},
    {name: "Klee", element: Element.PYRO, weapon: Weapon.CATALYST, rarity: 5},
    {name: "Kujou Sara", element: Element.ELECTRO, weapon: Weapon.BOW, rarity: 4},
    {name: "Kuki Shinobu", element: Element.HYDRO, weapon: Weapon.SWORD, rarity: 4},
    {name: "Layla", element: Element.ANEMO, weapon: Weapon.BOW, rarity: 4},
    {name: "Lisa", element: Element.ELECTRO, weapon: Weapon.CATALYST, rarity: 4},
    {name: "Lynette", element: Element.ANEMO, weapon: Weapon.BOW, rarity: 4},
    {name: "Lyney", element: Element.HYDRO, weapon: Weapon.CATALYST, rarity: 4},
    {name: "Mika", element: Element.ELECTRO, weapon: Weapon.CLAYMORE, rarity: 4},
    {name: "Mona", element: Element.HYDRO, weapon: Weapon.CATALYST, rarity: 5},
    {name: "Nahida", element: Element.PYRO, weapon: Weapon.POLEARM, rarity: 4},
    {name: "Navia", element: Element.GEO, weapon: Weapon.CLAYMORE, rarity: 5},
    {name: "Neuvillette", element: Element.ANEMO, weapon: Weapon.CATALYST, rarity: 4},
    {name: "Nilou", element: Element.ELECTRO, weapon: Weapon.CLAYMORE, rarity: 4},
    {name: "Ningguang", element: Element.GEO, weapon: Weapon.CATALYST, rarity: 4},
    {name: "Noelle", element: Element.GEO, weapon: Weapon.CLAYMORE, rarity: 4},
    {name: "Qiqi", element: Element.CRYO, weapon: Weapon.SWORD, rarity: 5},
    {name: "Raiden Shogun", element: Element.ELECTRO, weapon: Weapon.POLEARM, rarity: 5},
    {name: "Razor", element: Element.ELECTRO, weapon: Weapon.CLAYMORE, rarity: 4},
    {name: "Rosaria", element: Element.CRYO, weapon: Weapon.POLEARM, rarity: 4},
    {name: "Sangonomiya Kokomi", element: Element.HYDRO, weapon: Weapon.CATALYST, rarity: 5},
    {name: "Sayu", element: Element.ANEMO, weapon: Weapon.CLAYMORE, rarity: 4},
    {name: "Sethos", element: Element.GEO, weapon: Weapon.BOW, rarity: 4},
    {name: "Shenhe", element: Element.CRYO, weapon: Weapon.POLEARM, rarity: 5},
    {name: "Shikanoin Heizou", element: Element.ELECTRO, weapon: Weapon.CLAYMORE, rarity: 4},
    {name: "Sucrose", element: Element.ANEMO, weapon: Weapon.CATALYST, rarity: 4},
    {name: "Tartaglia", element: Element.HYDRO, weapon: Weapon.BOW, rarity: 5},
    {name: "Thoma", element: Element.PYRO, weapon: Weapon.POLEARM, rarity: 4},
    {name: "Tighnari", element: Element.ELECTRO, weapon: Weapon.CATALYST, rarity: 4},
    {name: "Traveler", element: Element.GEO, weapon: Weapon.SWORD, rarity: 5},
    {name: "Venti", element: Element.ANEMO, weapon: Weapon.BOW, rarity: 5},
    {name: "Wanderer", element: Element.ANEMO, weapon: Weapon.CATALYST, rarity: 4},
    {name: "Wriothesley", element: Element.ELECTRO, weapon: Weapon.BOW, rarity: 4},
    {name: "Xiangling", element: Element.PYRO, weapon: Weapon.POLEARM, rarity: 4},
    {name: "Xianyun", element: Element.CRYO, weapon: Weapon.CLAYMORE, rarity: 4},
    {name: "Xiao", element: Element.ANEMO, weapon: Weapon.POLEARM, rarity: 5},
    {name: "Xinqgiu", element: Element.HYDRO, weapon: Weapon.SWORD, rarity: 4},
    {name: "Xinyan", element: Element.PYRO, weapon: Weapon.CLAYMORE, rarity: 4},
    {name: "Yae Miko", element: Element.ELECTRO, weapon: Weapon.SWORD, rarity: 5},
    {name: "Yanfei", element: Element.PYRO, weapon: Weapon.CATALYST, rarity: 4},
    {name: "Yaoyao", element: Element.DENDRO, weapon: Weapon.CATALYST, rarity: 4},
    {name: "Yelan", element: Element.HYDRO, weapon: Weapon.BOW, rarity: 5},
    {name: "Yoimiya", element: Element.PYRO, weapon: Weapon.BOW, rarity: 5},
    {name: "Yun Jin", element: Element.GEO, weapon: Weapon.POLEARM, rarity: 4},
    {name: "Zhongli", element: Element.GEO, weapon: Weapon.POLEARM, rarity: 5}
]